"""SpotBugs exclusion filter generator.

Generates a `spotbugs-exclude.xml` suitable for `spotbugs-maven-plugin`.

The defaults exclude false positives common in code generated by this project:
- EI_EXPOSE_REP / EI_EXPOSE_REP2: MyBatis-Plus entity classes return mutable
  arrays/lists (intentional, allows ORM update)
- NM_FIELD_NAMING_CONVENTION: Lombok @Data + @Builder generates fields that
  SpotBugs sometimes mis-flags
- NP_NULL_PARAM_DEREF_NONVIRTUAL: false positive on Optional.ofNullable chains
"""

from __future__ import annotations


DEFAULT_EXCLUDED_PATTERNS = [
    ["EI_EXPOSE_REP", "EI_EXPOSE_REP2"],  # entity mutable exposure
    ["NM_FIELD_NAMING_CONVENTION"],  # Lombok-generated field names
    ["NP_NULL_PARAM_DEREF_NONVIRTUAL"],  # Optional chain FP
]


def generate_spotbugs_exclude_xml(
    rule_id_groups: list[list[str]] | None = None,
    additional_path_patterns: list[str] | None = None,
) -> str:
    """Generate spotbugs-exclude.xml content.

    Args:
        rule_id_groups: list of rule-ID groups; each group becomes one
            <Match> element (OR within group, AND across groups)
        additional_path_patterns: extra path patterns to exclude entirely

    Returns:
        XML content suitable for `spotbugs.excludeFilterFile` plugin config.
    """
    groups = rule_id_groups if rule_id_groups is not None else DEFAULT_EXCLUDED_PATTERNS
    path_patterns = additional_path_patterns or []

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<FindBugsFilter>',
    ]
    for group in groups:
        if not group:
            continue
        bugs = " ".join(f'<Bug pattern="{rule}"/>' for rule in group)
        lines.append(f'    <Match>{bugs}</Match>')

    for path in path_patterns:
        lines.append(
            f'    <Match><Source name="~{path}"/></Match>'
        )

    lines.append('</FindBugsFilter>')
    return "\n".join(lines) + "\n"
